export type ease = 'ease'
export type easeIn = 'ease-in'
export type easeOut = 'ease-out'
export type easeInOut = 'ease-in-out'
export type linear = 'linear'
export type stepStart = 'step-start'
export type stepEnd = 'step-end'
